### ISSUE TITLE
`widget.NewTextGridFromString(xxx)` Seems to be garbled

### ISSUE THREAD

**Issue by kolapapa** [lusingander/fyne-font-example#3]
Thank you for your warehouse for saving me many detours. The button and entry settings are all very smooth.

But I encountered a weird problem, which is setting

```go
package main


func showMsg(vbox *fyne.Container, success bool, msg string) {
	green := &widget.CustomTextGridStyle{
		BGColor: &color.RGBA{
			R: 38, G: 194, B: 129, A: 255},
		FGColor: color.White}
	red := &widget.CustomTextGridStyle{
		BGColor: &color.RGBA{
			R: 240, G: 52, B: 52, A: 255},
		FGColor: color.White}

	color := green
	if !success {
		color = red
	}
	stateGrid := widget.NewTextGridFromString(msg)
	stateGrid.SetRowStyle(0, color)
	vbox.Add(stateGrid)
}


func main() {
	a := app.New()
	a.Settings().SetTheme(&myTheme{})
	w := a.NewWindow("你好window")
	button := widget.NewButton("测试Button", func() {})
	vbox := container.NewVBox()
	showMsg(vbox, true, "你好")
	h := container.NewVBox(button, vbox)
	w.Canvas().SetContent(h)
	w.ShowAndRun()
}
```
Still have a problem

![image](https://user-images.githubusercontent.com/17918689/140552498-2cc60afc-1589-4dfc-b3ed-2ad75b80e939.png)

**Comment by lusingander** [comment]
Did you have monospaced fonts set up? `TextGrid` seems to use monospaced fonts, so I think it needs to be set.

**Comment by kolapapa** [comment]
> Did you have monospaced fonts set up? `TextGrid` seems to use monospaced fonts, so I think it needs to be set.

I found a few fonts and they still can’t be displayed correctly after downloading...

**Comment by kolapapa** [comment]
https://github.com/fyne-io/fyne/issues/2623#issuecomment-962677317

```
os.Setenv("FYNE_FONT_MONOSPACE", "AlibabaPuHuiTi-Medium.ttf")
```

This solution solved my problem
